server.port=${PORT:8080}
spring.config.import=optional:file:./application-local.properties
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USERNAME:AI_MOVIE}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
gemini.api.key=${AQ.Ab8RN6LxBlnNZtvZDB5HkIX5e8FnMVc-puUDz961aYhqE_EbyQ}
gemini.model=${GEMINI_MODEL:gemini-2.0-flash}
